spring.data.mongodb.uri=mongodb://localhost:27017/DB_SanFelipe
server.port=8080




# Groq API
openrouter.api.key=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
openrouter.model=openai/gpt-4o-mini
